* 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
* 자바가 제공하는 예외 계층 구조
* Exception과 Error의 차이는?
* RuntimeException과 RE가 아닌 것의 차이는?
* 커스텀한 예외 만드는 방법

## 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)

#### 예외란? 
프로그램이 정상적인 처리에서 벗어나게 될 때 이를 처리하기 위한 방법.  
예로 배열의 인덱스를 초과한다던가, 정수를 0으로 나눈다거나

##### 예외처리 1. try catch
가장 기본적인 방법이다. try문 안에 행동을 정의하고 예외가 발생 했을때 catch문으로  
가서 예외가 났을 때의 행동을 한다.

    int a;
    try{
        c = 4/0;
        System.out.print("안녕하세여.");
    }catch(ArithmeticException e){
        c= -1;
    }

##### 예외처리 2. finally
위에 try문에서는 예외가 발생하면 catch문으로 가고 출력문은 실행이 되지 않는다.  
근데 만약 꼭 실행해야하는 문장 이였다면?
그럴때 finally를 사용한다. 모두 끝나고 무조건 실행되어야할때 사용.

    int a;
    try{
        c = 4/0;
    }catch(ArithmeticException e){
        c= -1;
    }finally{
        System.out.print("파이널 입니다.");
    }

##### 예외처리 3. throw, throws
throw는 예외를 생성할 때 사용한다.
밑에서 return을 할 수도 있지만 throw로 예외를 발생시키면  
divide를 사용할 때는 강제적으로 반환되는 예외를 처리해야한다. 
밑에 처럼 try문을 쓰든 throws를 쓰던가.

    public class Main {
    
        public static void main(String[]args){
    
            try {
                divide(1,2);
            } catch (Exception e) {
                e.printStackTrace();
            }
    
        }
        
        public static int divide(int i,int j) throws Exception {
            if(j == 0){
                throw new Exception("안됨");
            }
            int result=i/j;
            return result;
        }
    }

throws란? 예외를 다른 곳에서 처리하도록 떠 넘기는 거다.  
위에서도 throws가 있듯이 예외를 divide에서 만들고 main에서 처리하라고 떠 넘기는 거다.  
main에서는 그 예외를 try/catch로 잡아서 자기선에서 마무리 했다. main에서도 throws했으면 예외는 또  
위로 날라갔을 꺼다. 

## 자바가 제공하는 예외 계층 구조
![image](https://user-images.githubusercontent.com/60220562/104123133-a2653280-538c-11eb-8b95-b608554485f7.png)  
출처 : https://reference-m1.tistory.com/246  

자바에서 예외는 붉은색의 checked와 퍼런색의 unchecked가 있다.

#### 체크 예외
RuntimeException을 상속하지 않은 예외들이다. 예측이 가능하다.  
메소드 사용시 반드시 예최를 처리하는 코드를 작성해야한다. catch문으로 잡던가 throws로 자신을 호출한 클래스로 던지던가.  
체크 예외는 java 컴파일러와 jvm이 규칙을 지키는지 확인하기 때문에 Exception이 호출된다.  
#### 언체크 예외 
RuntimeException을 상속한 예외들이다. 예측이 불가능하다. 신경쓰지 않는한.    
언체크라고 불리는 이유는 명시적으로 예외를 강제하지 않기 때문에..  
따로 catch로 잡거나 throws로 선언하지 않아도 된다. 발생하지 않게 개발자가 주의해야한다.  

## Exception과 Error의 차이는?
![image](https://user-images.githubusercontent.com/60220562/104123990-86b05b00-5391-11eb-9189-2f21ad30cf98.png)  
에러 계층도 : https://m.blog.naver.com/PostView.nhn?blogId=justkukaro&logNo=220819945511&proxyReferer=https:%2F%2Fwww.google.com%2F  

Exception과는 다르게(try/catch...) 에러가 발생하면 코드를 고치지 않는한 해결이 불가능하다.  유명한 stackOverflow나 OutOfMemoryError 등이 있다.  

Exception - 개발자가 구현한 로직에서 발생, 발생해도 대처만 하면 정상작동  
Error - 시스템 레벨에서 발생  , 전부 예측불가의 언체크 예외, 코드를 고쳐야 정상작동  

## RuntimeException과 RE가 아닌 것의 차이는?
런타임오류는 컴파일시에 잡을 수 없다.  -> try/catch로 잡을 수는 있지만 잡지 말고 코드를 고치는게 좋다. 주의 깊게 코드를 작성하던가.  
런타임이 아닌 오류는 컴파일 시에 잡을 수 있다.  -> try/catch로 해결 가능  

## 커스텀한 예외 만드는 방법
사용자 정의 Exception이라고 부른다.  
class를 선언하고 예외를 상속 받으면 되는데 위에서 본 계층도 처럼 2가지를 상속 받을 수 있다.  
1. Exception  
![image](https://user-images.githubusercontent.com/60220562/104286833-eecd8100-54f8-11eb-8091-45a6a5b47620.png)  
> * 반드시 오류를 처리 해야만 하는 Exception
> * 예외를 처리하지 않으면 컴파을 오류가 발생
> ![image](https://user-images.githubusercontent.com/60220562/104288410-19b8d480-54fb-11eb-9e3b-8ac11900f11f.png)  
2. RuntimeException  
![image](https://user-images.githubusercontent.com/60220562/104286893-06a50500-54f9-11eb-8604-ea84eaff40d5.png)  
> * 예외를 처리하지 않아도 컴파일 시에는 오류를 발생 시키진 않는다.
> ![image](https://user-images.githubusercontent.com/60220562/104288191-d199b200-54fa-11eb-8939-2c62bf6e84b7.png)  
